# Travis has pretty old gcc on precise and
# newer node causes dependencies to need C++11 compilers
sudo: false
dist: trusty

language: node_js
node_js:
  - "lts/*"
  - "node"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run deploy:prod

after_success:
  - npm run codecov

notifications:
  slack:
    secure: jocMgA4z6nHD7ZI7vQWsp6Tblpym1ugwQKZi6SZGUqxEFxoJrpwha7kDk5aQO5abe5jf55qlFxPytoP1nz35GzBUwfzFi8rGBmT27HYL9N+4f3UNMkppveLWveSZuU+ssp1vl5LBvo5kVrKnzTSAJaXEfIQAx1ttyOB+AxFlc/EtiPhIFsD2YqAv2kpJ4R/3wFQ/ZixHzjM2Yk5ER2TSlxdLaeHRnVG/Y8fZiuO4EtVOEzNyCDN215QXW04t2DihxDIYa5wJqHMJYJU5K0GARkdfJdHyqq1pGZzCYNxFaBJ7oQklk7r0LMtSsC5PTSgMQTac4jxijPXxr+5gZjMgfcDQA1z3aPRZnim2rsoepv2M5y4bkezs6RfYYCHOYbsF7Bv9kshP3wVDQpU44CkSknkCCr3hznydbUHFsIJnfMgkIlQIQQl6GD29FoR726hjWYwJ9q6m1CdliQbRHXBmjioZ6py73tWmiGdwvDlPxlsu3ABLQFUcLQh1kGQTdut88TmHwyXeSGJucIl4bJg+OfrCYg9TACByu5SRr/l55es/M3m3+7tNPzwWlu0wzgnq8Pw2QkE24ya1/j8bUXDLZGcaqCJOeKWj4MqH4mPUXoRxlQiSGouXS1nsIFa+YBwqL02nWfrAHEmtZStbU9lzx55bzM2IPjntfvU8NRODzeA=
