# Continuous integration (CI) triggers cause a pipeline to run whenever you push
# an update to the specified branches or you push specified tags.
trigger:
  batch: true
  branches:
    include:
    - main
  paths:
    exclude:
    - README.md

# Opt out of pull request validation
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: tiedonohjaus-pipelines
    type: git
    # Azure DevOps project/repository
    name: tiedonohjaus/tiedonohjaus-pipelines

extends:
  # Filename in Azure DevOps Repository (note possible -ui or -api)
  # Django example: azure-pipelines-tiedonohjaus-api-release.yml
  # Drupal example: azure-pipelines-drupal-release.yml
  template: azure-pipelines-build-tiedonohjaus-ui-test.yml@tiedonohjaus-pipelines
  #parameters:
    #imagetag: ${{ parameters.imagetag }}
