version: '3.8'

services:
  app:
    platform: linux/amd64
    ports:
      - 3000:8080
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    env_file:
      - .env
    volumes:
      - '.:/app'
      - '/app/node_modules'
    container_name: helerm-ui
