version: '3.8'

services:
  app:
    platform: linux/amd64
    ports:
      - ${PORT}:8000
    build:
      context: .
      target: ${DOCKER_TARGET:-development}
    volumes:
      - '.:/app'
      - '/app/node_modules'
    container_name: helerm-ui
