# Don't allow dependencies to be used before they have been released for at least 1 week
minimumReleaseAge: 10080

# Don't warn about ignored build scripts
ignoredBuiltDependencies: []

# Hoist all dependencies to the root of node_modules, for better compatibility with packages that expect flat node_modules
shamefullyHoist: true

overrides:
  'brace-expansion': '>=5.0.9'
  'minimatch': '^10.2.4'
  'tmp': '>=0.2.6'
  'immutable': '>=4.3.9'
  'fast-uri': '>=3.1.6'
  'undici': '^7.29.0'
  'js-yaml': '>=4.3.1'
  'postcss': '>=8.5.18'

allowBuilds:
  esbuild: true
  unrs-resolver: true
